# This is a basic workflow to help you get started with Actions

name: Update labels

# Controls when the workflow will run
on:
  workflow_dispatch:

jobs:
  run-command:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install GH CLI
        uses: dev-hanz-ops/install-gh-cli-action@v0.1.0

      
      - name: Run command on repos
        run: |
          repos=("owner1/repo1" "owner2/repo2" "owner3/repo3")
          
          for repo in "${repos[@]}"; do
            gh label clone younesStrittmatter/test2 --repo younesStrittmatter/test
          done
