# This is a basic workflow to help you get started with Actions

name: Update labels

# Controls when the workflow will run
on:
  workflow_dispatch:

jobs:
  run-command:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install GH CLI
        uses: dev-hanz-ops/install-gh-cli-action@v0.1.0

      
      - name: Run command on repos
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          repos=("younesStrittmatter/test")
          
          for repo in "${repos[@]}"; do
            gh label clone younesStrittmatter/test2 --repo "$repo"
          done
